### ISSUE TITLE
Provide URL Field on Example/Showcase Page for Testing

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/iiif-react-media-player#58]
### Description
In a previous version of the IIIF player, there was a static page built with a field for entering an arbitrary URL for a manifest that would then load in the player. This would be nice to have again in the current repository. The existing page could be repurposed or a new one created.

### Done Looks Like
- The styleguidist static doc site contains a landing page to serve as a demo page for the player (https://samvera-labs.github.io/iiif-react-media-player/)

**Comment by Dananji** [comment]
The new component library is written in such a way that we get exportable components out of it. And the input field for the manifest URL is something we will be using for the demo static page (and not something we want to be part of the exportable components). And I was not sure how this would go with the architecture of the project, so I had a small discussion with Adam. And from that, we realized adding a text field to this would not be identical to adding the text field for the previous component, since the components we see in the static page is what you get when you use this component library in your application. And also this is accomplished by the styleguidist docs provided text editor for each component in the static page.

The easier way to do this as we discussed is as follows;
The styleguidist docs are build in such a way that the user can interact with the components using the text editor that comes with each component. Using this, anyone on the page can change the way the component behaves by changing the code as well as its inputs. So by using this the URL of the manifest can be changed. To make this more clear for the user we can add a block of comment in the text editor below the player component so that, the user is aware this editor can be used as an input field for the component's props.

![Screenshot from 2021-01-20 17-10-16.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/f9359530-56ef-4d1e-9f08-21d4feef3a7c)
Other options would be:
- Add a text field component and use props in the player component to enable/disable it (this might be confusing when you use this in a real application)
- Build a standalone application like we have for the timeliner, so that we can import the components into that host application and build a text field in that host application. This then can be used to provide a manifest URL to the player/structured navigation components.
